{{- if and .Values.openwebui.persistence.enabled (not .Values.openwebui.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hearthai.claimName" . }}
  labels:
    {{- include "hearthai.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  {{- if ne .Values.openwebui.persistence.storageClass nil }}
  storageClassName: {{ .Values.openwebui.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.openwebui.persistence.size }}
{{- end }}
